------------Concencenssionaria--------------
CREATE TABLE CONCES
(
    IDC 	NUMBER(3) PRIMARY KEY, 
    NOME 	VARCHAR2(50) NOT NULL,
    ENDE 	VARCHAR2(70),
    BAIRRO 	VARCHAR2(30),
    CIDADE 	VARCHAR2(50)
);
--------------------Marca---------------------
CREATE TABLE MARCA
(
	IDMARCA		NUMBER(5) PRIMARY KEY,
	DESCRIÇAO	VARCHAR2(30) NOT NULL
);
------------------Modelo------------------------
CREATE TABLE MODELO
(
	IDMOD 		NUMBER(5) PRIMARY KEY,
	DESCRIÇAO 	VARCHAR2(50) NOT NULL,
	IDMARCA 	NUMBER(5) REFERENCES MARCA(IDMARCA)
);
------------Veiculo---------------------------------
CREATE TABLE VEICULOS
(
	IDVEIC	NUMBER(6) PRIMARY KEY,
	CHASSI	VARCHAR2(20) NOT NULL UNIQUE,
	PLACA	VARCHAR2(20),
	COR		VARCHAR2(15) NOT NULL,
	ANO		NUMBER(4) NOT NULL,
	VENDIDO	CHAR(1) DEFAULT 'N',
	IDC 	NUMBER(3) REFERENCES CONCES(IDC),
	IDMOD	NUMBER(5) REFERENCES MODELO(IDMOD),
	CONSTRAINT chk_vendido CHECK (VENDIDO IN ('S','N'))
);
--------------ClienteTEC--------------------------------
CREATE TABLE CLIENTEC
(
    IDCLI 	NUMBER(5) PRIMARY KEY,
    NOME 	VARCHAR2(40) NOT NULL,
    TELEF 	VARCHAR2(20),
    TIPOCLI VARCHAR2(1),
    CNPJ 	NUMBER(15),
	CPF	 	NUMBER(15),
	CONSTRAINT tipo_cli_chk	CHECK (TIPOCLI IN ('F','J'))
);
-------------------Cliente Veiculo----------------------
CREATE TABLE CLIENTEVEIC
(
	IDCLI		NUMBER(5) REFERENCES CLIENTEC(IDCLI),
	IDVEIC		NUMBER(6) REFERENCES VEICULOS(IDVEIC),
	NF			NUMBER(6),
	DTCOMPRA	DATE,
	PRIMARY KEY (IDCLI, IDVEIC)
);





